name: 📚 Benchmark Dataset Request
description: Do you think a particular benchmark dataset is missing in EuroEval?
title: "[BENCHMARK DATASET REQUEST] <dataset-name>"
labels: "benchmark dataset request"
type: task

body:
- type: input
  attributes:
    label: Dataset name
    description: What is the name of the dataset?
  validations:
    required: true
- type: input
  attributes:
    label: Dataset link
    description: >
      Please give a link to where the dataset is hosted (doesn't have to be on the
      Hugging Face Hub)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Dataset languages
    description: What languages is the dataset in?
    options:
      - label: Bulgarian
      - label: Croatian
      - label: Czech
      - label: Danish
      - label: Dutch
      - label: English
      - label: Estonian
      - label: Faroese
      - label: Finnish
      - label: French
      - label: German
      - label: Greek
      - label: Icelandic
      - label: Italian
      - label: Latvian
      - label: Lithuanian
      - label: Norwegian (Bokmål or Nynorsk)
      - label: Polish
      - label: Portuguese
      - label: Serbian
      - label: Slovak
      - label: Slovenian
      - label: Spanish
      - label: Swedish
      - label: Ukrainian
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the dataset
    description: >
      Describe what the dataset is measuring, and why you think it is important to
      include it as a benchmark dataset in EuroEval.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
