"""Constants used for the template configurations."""

NER_TAG_MAPPING = {
    "per": {
        "da": "person",
        "de": "person",
        "en": "person",
        "es": "persona",
        "fo": "persónur",
        "fr": "personne",
        "is": "einstaklingur",
        "it": "persona",
        "nb": "person",
        "nl": "persoon",
        "nn": "person",
        "no": "person",
        "sv": "person",
    },
    "loc": {
        "da": "sted",
        "de": "ort",
        "en": "location",
        "es": "lugar",
        "fo": "staður",
        "fr": "lieu",
        "is": "staðsetning",
        "it": "posizione",
        "nb": "sted",
        "nl": "locatie",
        "nn": "sted",
        "no": "sted",
        "sv": "plats",
    },
    "org": {
        "da": "organisation",
        "de": "organisation",
        "en": "organization",
        "es": "organización",
        "fo": "felagsskapur",
        "fr": "organisation",
        "is": "stofnun",
        "it": "organizzazione",
        "nb": "organisasjon",
        "nl": "organisatie",
        "nn": "organisasjon",
        "no": "organisasjon",
        "sv": "organisation",
    },
    "misc": {
        "da": "diverse",
        "de": "verschiedenes",
        "en": "miscellaneous",
        "es": "misceláneo",
        "fo": "ymiskt",
        "fr": "divers",
        "is": "ýmislegt",
        "it": "varie",
        "nb": "diverse",
        "nl": "diversen",
        "nn": "diverse",
        "no": "diverse",
        "sv": "diverse",
    },
}

LA_LABEL_MAPPING = {
    "correct": {
        "da": "ja",
        "de": "ja",
        "en": "yes",
        "es": "sí",
        "fo": "ja",
        "fr": "oui",
        "is": "já",
        "it": "si",
        "nb": "ja",
        "nl": "ja",
        "nn": "ja",
        "no": "ja",
        "sv": "ja",
    },
    "incorrect": {
        "da": "nej",
        "de": "nein",
        "en": "no",
        "es": "no",
        "fo": "nei",
        "fr": "non",
        "is": "nei",
        "it": "no",
        "nb": "nei",
        "nl": "nee",
        "nn": "nei",
        "no": "nei",
        "sv": "nej",
    },
}
